backend:
  name: git-gateway
  branch: master

# Enable this when running the backend proxy server with `npx netlify-cms-proxy-server`
# local_backend: true

media_folder: static/images
public_folder: ../../static/images

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/pages/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - { label: "CTA Text", name: "cta_text", widget: "string" }
          - { label: "CTA Link", name: "cta_link", widget: "string" }
          - label: "Featured Projects"
            name: "projects"
            widget: "relation"
            collection: "project"
            searchFields: ["title", "subtitle"]
            displayFields: ["title"]
            valueField: "title"
            multiple: true
      - label: "About"
        name: "about"
        file: "content/pages/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - { label: "Form Success", name: "formSuccess", widget: "string" }
          - {
              label: "Form Fields",
              name: "formFields",
              widget: "list",
              collapsed: false,
              fields:
                [
                  {
                    label: "Type",
                    name: "type",
                    widget: "select",
                    default: "text",
                    options:
                      [
                        { label: "Text", value: "text" },
                        { label: "Email", value: "email" },
                        { label: "Text Area", value: "textarea" },
                      ],
                  },
                  { label: "Label", name: "label", widget: "string" },
                  { label: "Placeholder", name: "placeholder", widget: "string" },
                  {
                    label: "Required",
                    name: "required",
                    widget: select,
                    default: false,
                    options:
                      [
                        { label: "Yes", value: true },
                        { label: "No", value: false },
                      ],
                  },
                ],
            }
  - name: "project"
    label: "Project"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
